baseURL: http://quasili.ch/
languageCode: en-us
title: Quasili Software
theme: "PaperMod"

params:
    profileMode:
        enabled: true
        title: "Quasili Software LLC" # optional default will be site title
        subtitle: "Because we love complexity"
        imageUrl: "<image link>" # optional
        imageTitle: "A graph of a quasi-linear complexity." # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        #buttons:
            #- name: Archive
            #  url: "/archive"
            #- name: Github

    socialIcons: # optional
        - name: "Twitter"
          url: "https://twitter.com/anomalroil"
        - name: "Github"
          url: "https://github.com/Quasili-Software"
        - name: "Email"
          url: "mailto:yolan@quasili.ch"
    env: production
